-- ============================================================================
-- 0050_restrict_sync_agents_realtime.sql
-- BIENENHAUS - Restringir ejecución de sync_agents_realtime
-- ============================================================================
-- Contexto:
--   El linter de seguridad de Supabase (advisor 0028) reporta que la función
--   public.sync_agents_realtime() es ejecutable por el rol `anon` como
--   SECURITY DEFINER vía /rest/v1/rpc/sync_agents_realtime.
--
--   Análisis de riesgo:
--   - sync_agents_realtime() es una trigger function (AFTER INSERT/UPDATE/
--     DELETE ON agents) que mantiene la tabla shadow agents_realtime para
--     Realtime de la landing.
--   - NO se referencia en ninguna RLS policy (verificado contra pg_policies).
--   - anon NO tiene grants sobre la tabla `agents` (por eso existe la vista
--     agents_public como proyección pública), por lo que nunca puede disparar
--     el trigger. Solo authenticated (staff) y service_role (edge functions)
--     realizan DML sobre agents.
--   - El único vector era la invocación directa del RPC por anon, que no tiene
--     ningún caso de uso legítimo.
--
-- Decisión:
--   Revocar EXECUTE de anon/public y mantenerlo únicamente para
--   authenticated + service_role (mismo patrón que 0049).
-- ============================================================================

revoke execute on function public.sync_agents_realtime() from anon, public;
grant execute on function public.sync_agents_realtime() to authenticated, service_role;

-- ============================================================================
-- Excepciones aceptadas del advisor de seguridad (documentadas, NO corregir):
--
-- 1) public.agents_public (lint 0010 security_definer_view, ERROR)
--    Vista con security_invoker = false POR DISEÑO (ver 0031): anon no tiene
--    grants sobre `agents` y la vista es la única puerta pública, filtrando
--    columnas (excluye email/phone/social/permissions/commission/schedule) y
--    filas (is_active AND deleted_at IS NULL). Convertirla a security_invoker
--    obligaría a otorgar SELECT de anon sobre `agents` completa, EXPONIENDO
--    datos sensibles por PostgREST directo. El WHERE explícito es la garantía.
--
-- 2) is_admin() / is_staff() / is_super_admin() / has_role()
--    (lint 0028 anon_security_definer_function_executable, WARN)
--    Ejecutables por anon porque ~40 tablas tienen policies con roles
--    {public} (incluye anon) que evalúan estos helpers en cada consulta;
--    revocar EXECUTE rompería el acceso público (ERROR en vez de 0 filas).
--    Son benignos: para anon (auth.uid() = NULL) siempre devuelven false.
--
-- 3) submit_contact() / subscribe_newsletter() (lint 0028, WARN)
--    Funciones públicas de la landing por diseño (formularios con honeypot
--    + rate limit).
-- ============================================================================
